<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Le calendrier de l'avent des développeurs</title>

        <link rel="icon" href="/static/images/icons/favicon.svg" type="image/svg+xml">
        <link rel="stylesheet" href="/static/styles/main.css">
    </head>
    <body>
        <?php require_once dirname(__DIR__) . "/Components/navbar.phtml" ?>
        @[content]
        <?php require_once dirname(__DIR__) . "/Components/footer.phtml" ?>
    </body>
</html>
